services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Kitzberger\Usebouncer\:
    resource: '../Classes/*'

  Kitzberger\Usebouncer\Service\Api:
    public: true

  Kitzberger\Usebouncer\Command\TestCommand:
    tags:
      - name: 'console.command'
        command: 'usebouncer:test'
        schedulable: false
